sass:
  load_paths:
    - _sass
    - node_modules

destination: ./docs

baseurl: /docs

exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - index.html
  - Gemfile
  - Gemfile.lock

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

plugins:
  - octopress-autoprefixer
  - jekyll-compress-images
